owner: ваш-github-username
repo: ваш-репозиторий
sites:
  - name: Telegram Bot Webhook
    url: https://ваш-бот.onrender.com/webhook
    method: POST
    interval: 5
    headers:
      - key: User-Agent
        value: Upptime/1.0
    expectStatus: 200
    timeout: 30000

  - name: Telegram Bot Root
    url: https://ваш-бот.onrender.com
    method: GET
    interval: 5
    headers:
      - key: User-Agent
        value: Upptime/1.0
    expectStatus: 200
    timeout: 30000

status-website:
  baseUrl: /ваш-репозиторий
