owner: Phirdorri  # Например, ivan-petrov
repo: tlg-bot-monitor       # Например, telegram-bot-monitor
sites:
  - name: Telegram Bot Webhook
    url: https://lite-tg-shop-bot.onrender.com/webhook
    method: POST             # Критично для Render!
    interval: 5              # Проверка каждые 5 минут
status-website:
  baseUrl: /tlg-bot-monitor  # Например, /telegram-bot-monitor
