owner: Phirdorri
repo: tlg-bot-monitor
sites:
  - name: Telegram Bot Webhook
    url: https://lite-tg-shop-bot.onrender.com/webhook
    method: POST
    interval: 5
    headers:
      - key: User-Agent
        value: Upptime/1.0
    expectStatus: 200
    timeout: 30000

  - name: Telegram Bot Root
    url: https://lite-tg-shop-bot.onrender.com
    method: GET
    interval: 5
    headers:
      - key: User-Agent
        value: Upptime/1.0
    expectStatus: 200
    timeout: 30000

status-website:
  baseUrl: /tlg-bot-monitor
